// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Multi_Library_Management_Api.Data;

#nullable disable

namespace Multi_Library_Management_Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260511105503_AddBatchSystem")]
    partial class AddBatchSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Multi_Library_Management_Api.Models.AttendanceLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("AccessGranted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ExitTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("AttendanceLogs");
                });

            modelBuilder.Entity("Multi_Library_Management_Api.Models.Batch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(UTC_TIMESTAMP())");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<int>("LibraryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("LibraryId");

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("Multi_Library_Management_Api.Models.Floor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("FloorNumber")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<int>("LibraryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("LibraryId");

                    b.ToTable("Floors");
                });

            modelBuilder.Entity("Multi_Library_Management_Api.Models.GateAccessLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("AccessDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsAllowed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RFIDCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Reason")
                        .HasColumnType("longtext");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("GateAccessLogs");
                });

            modelBuilder.Entity("Multi_Library_Management_Api.Models.Library", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(UTC_TIMESTAMP())");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Mobile")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Pincode")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Libraries");
                });

            modelBuilder.Entity("Multi_Library_Management_Api.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("NextDueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("RegistrationId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Multi_Library_Management_Api.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(UTC_TIMESTAMP())");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create library",
                            IsActive = true,
                            Module = "Library",
                            Name = "CREATE_LIBRARY"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Edit library",
                            IsActive = true,
                            Module = "Library",
                            Name = "EDIT_LIBRARY"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Delete library",
                            IsActive = true,
                            Module = "Library",
                            Name = "DELETE_LIBRARY"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View library",
                            IsActive = true,
                            Module = "Library",
                            Name = "VIEW_LIBRARY"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create floor",
                            IsActive = true,
                            Module = "Floor",
                            Name = "CREATE_FLOOR"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Edit floor",
                            IsActive = true,
                            Module = "Floor",
                            Name = "EDIT_FLOOR"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Delete floor",
                            IsActive = true,
                            Module = "Floor",
                            Name = "DELETE_FLOOR"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View floor",
                            IsActive = true,
                            Module = "Floor",
                            Name = "VIEW_FLOOR"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create section",
                            IsActive = true,
                            Module = "Section",
                            Name = "CREATE_SECTION"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Edit section",
                            IsActive = true,
                            Module = "Section",
                            Name = "EDIT_SECTION"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Delete section",
                            IsActive = true,
                            Module = "Section",
                            Name = "DELETE_SECTION"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View section",
                            IsActive = true,
                            Module = "Section",
                            Name = "VIEW_SECTION"
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create table",
                            IsActive = true,
                            Module = "Table",
                            Name = "CREATE_TABLE"
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Edit table",
                            IsActive = true,
                            Module = "Table",
                            Name = "EDIT_TABLE"
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Delete table",
                            IsActive = true,
                            Module = "Table",
                            Name = "DELETE_TABLE"
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View table",
                            IsActive = true,
                            Module = "Table",
                            Name = "VIEW_TABLE"
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create seat",
                            IsActive = true,
                            Module = "Seat",
                            Name = "CREATE_SEAT"
                        },
                        new
                        {
                            Id = 18,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Edit seat",
                            IsActive = true,
                            Module = "Seat",
                            Name = "EDIT_SEAT"
                        },
                        new
                        {
                            Id = 19,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Delete seat",
                            IsActive = true,
                            Module = "Seat",
                            Name = "DELETE_SEAT"
                        },
                        new
                        {
                            Id = 20,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View seat",
                            IsActive = true,
                            Module = "Seat",
                            Name = "VIEW_SEAT"
                        },
                        new
                        {
                            Id = 21,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create student",
                            IsActive = true,
                            Module = "Student",
                            Name = "CREATE_STUDENT"
                        },
                        new
                        {
                            Id = 22,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Edit student",
                            IsActive = true,
                            Module = "Student",
                            Name = "EDIT_STUDENT"
                        },
                        new
                        {
                            Id = 23,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Delete student",
                            IsActive = true,
                            Module = "Student",
                            Name = "DELETE_STUDENT"
                        },
                        new
                        {
                            Id = 24,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View student",
                            IsActive = true,
                            Module = "Student",
                            Name = "VIEW_STUDENT"
                        },
                        new
                        {
                            Id = 25,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create registration",
                            IsActive = true,
                            Module = "Registration",
                            Name = "CREATE_REGISTRATION"
                        },
                        new
                        {
                            Id = 26,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Edit registration",
                            IsActive = true,
                            Module = "Registration",
                            Name = "EDIT_REGISTRATION"
                        },
                        new
                        {
                            Id = 27,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View registration",
                            IsActive = true,
                            Module = "Registration",
                            Name = "VIEW_REGISTRATION"
                        },
                        new
                        {
                            Id = 28,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Create payment",
                            IsActive = true,
                            Module = "Payment",
                            Name = "CREATE_PAYMENT"
                        },
                        new
                        {
                            Id = 29,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View payment",
                            IsActive = true,
                            Module = "Payment",
                            Name = "VIEW_PAYMENT"
                        },
                        new
                        {
                            Id = 30,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "View reports",
                            IsActive = true,
                            Module = "Report",
                            Name = "VIEW_REPORT"
                        },
                        new
                        {
                            Id = 31,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Manage RFID gate access",
                            IsActive = true,
                            Module = "RFID",
                            Name = "RFID_ACCESS"
                        });
                });

            modelBuilder.Entity("Multi_Library_Management_Api.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(UTC_TIMESTAMP())");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<int?>("LibraryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("LibraryId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Full system access",
                            IsActive = true,
                            Name = "SuperAdmin"
                        });
                });

            modelBuilder.Entity("Multi_Library_Management_Api.Models.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PermissionId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            PermissionId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 3,
                            PermissionId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            PermissionId = 4,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 5,
                            PermissionId = 5,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 6,
                            PermissionId = 6,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 7,
                            PermissionId = 7,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 8,
                            PermissionId = 8,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 9,
                            PermissionId = 9,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 10,
                            PermissionId = 10,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 11,
                            PermissionId = 11,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 12,
                            PermissionId = 12,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 13,
                            PermissionId = 13,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 14,
                            PermissionId = 14,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 15,
                            PermissionId = 15,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 16,
                            PermissionId = 16,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 17,
                            PermissionId = 17,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 18,
                            PermissionId = 18,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 19,
                            PermissionId = 19,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 20,
                            PermissionId = 20,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 21,
                            PermissionId = 21,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 22,
                            PermissionId = 22,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 23,
                            PermissionId = 23,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 24,
                            PermissionId = 24,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 25,
                            PermissionId = 25,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 26,
                            PermissionId = 26,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 27,
                            PermissionId = 27,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 28,
                            PermissionId = 28,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 29,
                            PermissionId = 29,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 30,
                            PermissionId = 30,
                            RoleId = 1
                        },
                        new
                        {
                            Id = 31,
                            PermissionId = 31,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Multi_Library_Management_Api.Models.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("FloorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("Multi_Library_Management_Api.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(UTC_TIMESTAMP())");

                    b.Property<string>("FatherName")
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<int>("LibraryId")
                        .HasColumnType("int");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Photo")
                        .HasColumnType("longtext");

                    b.Property<string>("RFIDCode")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("LibraryId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Multi_Library_Management_Api.Models.StudentRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("MonthlyAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("RegistrationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(UTC_TIMESTAMP())");

                    b.Property<decimal>("SecurityAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TableSeatId")
                        .HasColumnType("int");

                    b.Property<int?>("TableSeatId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("StudentId");

                    b.HasIndex("TableSeatId");

                    b.HasIndex("TableSeatId1");

                    b.ToTable("StudentRegistrations");
                });

            modelBuilder.Entity("Multi_Library_Management_Api.Models.TableSeat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsOccupied")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<string>("TableNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("TableSeats");
                });

            modelBuilder.Entity("Multi_Library_Management_Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("(UTC_TIMESTAMP())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsSuperadmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<int?>("LibraryId")
                        .HasColumnType("int");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("LibraryId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "superadmin@library.com",
                            FullName = "Super Admin",
                            IsActive = true,
                            IsSuperadmin = true,
                            Mobile = "9999999999",
                            Password = "Admin@123",
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Multi_Library_Management_Api.Models.AttendanceLog", b =>
                {
                    b.HasOne("Multi_Library_Management_Api.Models.Student", "Student")
                        .WithMany("AttendanceLogs")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Multi_Library_Management_Api.Models.Batch", b =>
                {
                    b.HasOne("Multi_Library_Management_Api.Models.Library", "Library")
                        .WithMany()
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Library");
                });

            modelBuilder.Entity("Multi_Library_Management_Api.Models.Floor", b =>
                {
                    b.HasOne("Multi_Library_Management_Api.Models.Library", "Library")
                        .WithMany("Floors")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Library");
                });

            modelBuilder.Entity("Multi_Library_Management_Api.Models.GateAccessLog", b =>
                {
                    b.HasOne("Multi_Library_Management_Api.Models.Student", "Student")
                        .WithMany("GateAccessLogs")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Multi_Library_Management_Api.Models.Payment", b =>
                {
                    b.HasOne("Multi_Library_Management_Api.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Multi_Library_Management_Api.Models.StudentRegistration", "StudentRegistration")
                        .WithMany("Payments")
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("StudentRegistration");
                });

            modelBuilder.Entity("Multi_Library_Management_Api.Models.Role", b =>
                {
                    b.HasOne("Multi_Library_Management_Api.Models.Library", "Library")
                        .WithMany("Roles")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Library");
                });

            modelBuilder.Entity("Multi_Library_Management_Api.Models.RolePermission", b =>
                {
                    b.HasOne("Multi_Library_Management_Api.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Multi_Library_Management_Api.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Multi_Library_Management_Api.Models.Section", b =>
                {
                    b.HasOne("Multi_Library_Management_Api.Models.Floor", "Floor")
                        .WithMany("Sections")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Floor");
                });

            modelBuilder.Entity("Multi_Library_Management_Api.Models.Student", b =>
                {
                    b.HasOne("Multi_Library_Management_Api.Models.Library", "Library")
                        .WithMany("Students")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Library");
                });

            modelBuilder.Entity("Multi_Library_Management_Api.Models.StudentRegistration", b =>
                {
                    b.HasOne("Multi_Library_Management_Api.Models.Batch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Multi_Library_Management_Api.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Multi_Library_Management_Api.Models.Student", "Student")
                        .WithMany("StudentRegistrations")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Multi_Library_Management_Api.Models.TableSeat", "TableSeat")
                        .WithMany()
                        .HasForeignKey("TableSeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Multi_Library_Management_Api.Models.TableSeat", null)
                        .WithMany("StudentRegistrations")
                        .HasForeignKey("TableSeatId1");

                    b.Navigation("Batch");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Student");

                    b.Navigation("TableSeat");
                });

            modelBuilder.Entity("Multi_Library_Management_Api.Models.TableSeat", b =>
                {
                    b.HasOne("Multi_Library_Management_Api.Models.Section", "Section")
                        .WithMany("TableSeats")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Multi_Library_Management_Api.Models.User", b =>
                {
                    b.HasOne("Multi_Library_Management_Api.Models.Library", "Library")
                        .WithMany("Users")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Multi_Library_Management_Api.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Library");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Multi_Library_Management_Api.Models.Floor", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("Multi_Library_Management_Api.Models.Library", b =>
                {
                    b.Navigation("Floors");

                    b.Navigation("Roles");

                    b.Navigation("Students");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Multi_Library_Management_Api.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Multi_Library_Management_Api.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Multi_Library_Management_Api.Models.Section", b =>
                {
                    b.Navigation("TableSeats");
                });

            modelBuilder.Entity("Multi_Library_Management_Api.Models.Student", b =>
                {
                    b.Navigation("AttendanceLogs");

                    b.Navigation("GateAccessLogs");

                    b.Navigation("StudentRegistrations");
                });

            modelBuilder.Entity("Multi_Library_Management_Api.Models.StudentRegistration", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Multi_Library_Management_Api.Models.TableSeat", b =>
                {
                    b.Navigation("StudentRegistrations");
                });
#pragma warning restore 612, 618
        }
    }
}
